import type { Solid } from "./solids";
import type { StudLayout } from "@/lib/modules/framing/types";
import { formatLength } from "@/lib/units";

/**
 * Generate a parametric, human-editable OpenSCAD script from the solids.
 * Pure string templating — no three.js dependency.
 */
export function generateOpenSCAD(layout: StudLayout, solids: Solid[]): string {
  const L = formatLength(layout.input.length, { feetInches: true });
  const H = formatLength(layout.input.height, { feetInches: true });

  const lines: string[] = [
    `// HomeReno framing model — wall ${L} × ${H}`,
    `// ${layout.input.studSize} @ ${formatLength(layout.input.spacingOC)} OC, ${layout.input.topPlate} top plate`,
    `// Units: inches. Generated by engine ${layout.engineVersion}.`,
    ``,
    `$fn = 16;`,
    ``,
    `// One framing member: a box by center + size`,
    `module member(cx, cy, cz, sx, sy, sz) {`,
    `  translate([cx - sx/2, cy - sy/2, cz - sz/2]) cube([sx, sy, sz]);`,
    `}`,
    ``,
    `module wall_frame() {`,
  ];

  for (const s of solids) {
    const [cx, cy, cz] = s.position;
    const [sx, sy, sz] = s.size;
    lines.push(
      `  member(${cx.toFixed(4)}, ${cy.toFixed(4)}, ${cz.toFixed(4)}, ${sx.toFixed(4)}, ${sy.toFixed(4)}, ${sz.toFixed(4)}); // ${s.id}: ${s.label}`,
    );
  }

  lines.push(`}`, ``, `wall_frame();`, ``);
  return lines.join("\n");
}
