"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { computeFraming } from "@/lib/modules/framing";
import { WallElevation } from "@/components/svg/WallElevation";
import { CutListTable } from "@/components/outputs/CutListTable";
import { PackingDiagram } from "@/components/outputs/PackingDiagram";
import { NailingScheduleTable } from "@/components/outputs/NailingScheduleTable";
import { ShoppingList } from "@/components/outputs/ShoppingList";
import { useEditor } from "@/stores/editor";
import { useSettings } from "@/stores/settings";
import { formatLength } from "@/lib/units";

/**
 * One-page printable cut sheet. White paper, dark ink — browser
 * print-to-PDF is the export path (landscape letter).
 */
export default function PrintPage() {
  const wall = useEditor((s) => s.wall);
  const system = useSettings((s) => s.system);
  const [today, setToday] = useState("");
  useEffect(() => setToday(new Date().toLocaleDateString()), []);

  const output = useMemo(() => {
    try {
      return computeFraming(wall);
    } catch {
      return null;
    }
  }, [wall]);

  if (!output) {
    return <p className="p-6">Nothing to print — design a wall first.</p>;
  }

  return (
    <div className="print-sheet mx-auto min-h-screen w-full max-w-[10.5in] px-6 py-5">
      <div className="no-print mb-4 flex items-center justify-between">
        <Link href="/design" className="bp-dim text-[11px] uppercase tracking-widest underline">
          ← back to designer
        </Link>
        <button
          onClick={() => window.print()}
          className="bp-dim rounded-sm border border-bp-accent px-4 py-2 text-[11px] uppercase tracking-widest text-bp-accent"
        >
          Print / Save PDF
        </button>
      </div>

      {/* title block */}
      <div className="print-avoid-break mb-4 flex items-stretch justify-between border-2 border-bp-line">
        <div className="px-4 py-2">
          <h1 className="bp-panel-title text-xl">HomeReno — Framing Cut Sheet</h1>
          <p className="bp-dim text-[11px] text-bp-line-soft">
            Wall {formatLength(wall.length, { system, feetInches: true })} ×{" "}
            {formatLength(wall.height, { system, feetInches: true })} · {wall.studSize} @{" "}
            {formatLength(wall.spacingOC, { system })} OC · {wall.topPlate} top plate ·{" "}
            {wall.loadBearing ? "LOAD-BEARING" : "non-bearing"} · {wall.openings.length} opening(s)
          </p>
        </div>
        <div className="grid grid-cols-3 text-[10px]" style={{ minWidth: "260px" }}>
          <div className="border-l border-bp-line px-2 py-1">
            <div className="text-bp-line-soft">DATE</div>
            <div className="bp-dim">{today}</div>
          </div>
          <div className="border-l border-bp-line px-2 py-1">
            <div className="text-bp-line-soft">JURISDICTION</div>
            <div className="bp-dim">Wake Co, NC</div>
          </div>
          <div className="border-l border-bp-line px-2 py-1">
            <div className="text-bp-line-soft">SHEET</div>
            <div className="bp-dim">F-101</div>
          </div>
        </div>
      </div>

      {/* elevation */}
      <div className="print-avoid-break mb-4 border border-bp-line-faint p-2">
        <WallElevation layout={output.layout} system={system} showIds className="h-auto w-full" />
      </div>

      <div className="grid grid-cols-2 gap-6">
        <div className="print-avoid-break">
          <h2 className="bp-panel-title mb-2 text-sm">Cut List</h2>
          <CutListTable cutList={output.cutList} system={system} />
        </div>
        <div className="print-avoid-break">
          <h2 className="bp-panel-title mb-2 text-sm">Shopping List</h2>
          <ShoppingList lines={output.shopping} readOnly />
        </div>
      </div>

      <div className="print-avoid-break mt-4">
        <h2 className="bp-panel-title mb-2 text-sm">Cut Plan</h2>
        <PackingDiagram packing={output.packing} system={system} />
      </div>

      <div className="print-avoid-break mt-4">
        <h2 className="bp-panel-title mb-2 text-sm">Fastening Schedule</h2>
        <NailingScheduleTable nailing={output.nailing} />
      </div>

      <p className="bp-dim mt-4 text-[9px] text-bp-line-soft">
        Header sizes are rule-of-thumb (verify NCRC R602.7 for load-bearing openings). Generated by
        HomeReno · engine {output.layout.engineVersion}
      </p>
    </div>
  );
}
